### ISSUE TITLE
`no_std` build issue

### ISSUE THREAD

**Issue by vlabo** [zakarumych/ring-alloc#3]
Im trying to use the allocator in a `no_std` environment. But I'm having a issue with the build.
Im on nightly with `allocator_api` enabled.

Cargo.toml: 
```
ring-alloc = { version = "0.2.0", default-features = false, features = ["alloc", "nightly"] }
```

Error:
```
error[E0152]: found duplicate lang item `panic_impl`
  --> src/lib.rs:33:1
   |
33 | fn panic(info: &PanicInfo) -> ! {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: the lang item is first defined in crate `std` (which `allocator_api2` depends on)
```

I can't  pinpoint what exactly is using `std` in the `allocator_api2`

Can you point me to the right direction. Will be happy to submit a PR if I know what should I do.

**Comment by zakarumych** [comment]
The problem is that `ring-alloc` does not turn off default feature `std` of `allocator-api2`
